plugins:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false
