plugins:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 120

Style/Documentation:
  Enabled: false
