"use client";
import { useEffect, useState } from "react";
import { createEvent, IEvent, eventSchema } from "@/app/events/events.service";
import { Input } from "../../components/Input";
import { Button } from "@/app/components/Button";
import { Textarea } from "@/app/components/Textarea";
import { IToast, Toast } from "@/app/components/Toast";
import { validateOnBlur } from "@/app/utilities";
import { eventDuration } from "../events.helper";
import { DropDown } from "@/app/components/Dropdown";

export const CreateEventForm = ({ teams }: { teams: any }) => {
  const [toast, setToast] = useState<IToast>();
  const [errors, setErrors] = useState<{ [name: string]: string }>({});
  const [startTime, setStartTime] = useState("");
  const [endTime, setEndTime] = useState("");
  const [duration, setDuration] = useState<string | undefined>();

  const handleChange = async (
    event: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    validateOnBlur(event, eventSchema, setErrors);
  };

  const submitEventInformation = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const formEntries = Object.fromEntries(formData);
    const event: IEvent = {
      // id is generated by backend, so it is omitted here
      title: formEntries.title as string,
      description: formEntries.description as string,
      start_time: formEntries.start_time as string,
      end_time: formEntries.end_time as string,
      adult_slots: Number(formEntries.adult_slots),
      teenager_slots: Number(formEntries.teenager_slots),
      // creator id is set to current_user.id in the events_controller create action
      team_id: Number(formEntries.team_id),
    };
    try {
      eventSchema.validateSync(formEntries, {
        abortEarly: false,
      });
      createEvent(event)
        .then(async (response) => {
          setToast({
            message: "Event created",
            status: "success",
          });
        })
        .catch((error) => {
          setToast({ message: error.message, status: "error" });
        });
    } catch (validationError: any) {
      const formattedError = validationError.inner.reduce(
        (acc: any, err: any) => {
          acc[err.path] = err.message;
          return acc;
        },
        {}
      );
      setErrors(formattedError);
    }
  };

  useEffect(() => {
    if (startTime && endTime) {
      setDuration(eventDuration(startTime, endTime));
    }
  }, [startTime, endTime]);

  return (
    <>
      {toast && (
        <Toast
          message={toast.message}
          status={toast.status}
          onClose={() => setToast(undefined)}
        />
      )}

      <form
        onSubmit={submitEventInformation}
        className="flex flex-col gap-4 w-100"
      >
        <Input
          label="Event title"
          type="text"
          name="title"
          onBlur={handleChange}
          errorMessage={errors.title}
        />
        <Input
          label="Start"
          type="datetime-local"
          name="start_time"
          onBlur={handleChange}
          onInput={(e) => {
            setStartTime(e.currentTarget.value);
          }}
          errorMessage={errors.start_time}
        />
        <Input
          label="End"
          type="datetime-local"
          name="end_time"
          onBlur={handleChange}
          onInput={(e) => {
            setEndTime(e.currentTarget.value);
          }}
          errorMessage={errors.end_time}
        />
        {duration && <p>Duration: {duration}</p>}
        <Input
          label="Adult volunteers needed"
          type="number"
          name="adult_slots"
          onBlur={handleChange}
          errorMessage={errors.adult_slots}
        />
        <Input
          label="Teenager volunteers needed"
          type="number"
          name="teenager_slots"
          onBlur={handleChange}
          errorMessage={errors.teenager_slots}
        />
        <Textarea
          label="Event description"
          name="description"
          onBlur={handleChange}
          errorMessage={errors.description}
        />
        <DropDown
          choices={teams}
          name="team_id"
          label="Team"
          helpText="Please select a team"
          onBlur={handleChange}
          errorMessage={errors.team_id}
        />

        <Button type="submit" label="Create event" />
      </form>
    </>
  );
};
