"use client";
import { createEvent, IEvent } from "../events.service";
import { Input } from "../../components/Input";
import { Button } from "@/app/components/Button";

export const CreateEventForm = () => {
  const submitEventInformation = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const formEntries = Object.fromEntries(formData);
    const event: IEvent = {
      // id is generated by backend, so it is omitted here
      title: formEntries.title as string,
      description: formEntries.description as string,
      start_time: formEntries.start_time as string,
      end_time: formEntries.end_time as string,
      adult_slots: Number(formEntries.adult_slots),
      teenager_slots: Number(formEntries.teenager_slots),
      // creator id is set to current_user.id in the events_controller create action
      team_id: Number(formEntries.team_id),
    };
    try {
      createEvent(event);
    } catch (error) {
      console.error("Error creating event:", error);
    }
  };

  return (
    <form
    onSubmit={submitEventInformation}
    className="flex flex-col gap-4 w-100"
    >
      <Input
        label="Event Title"
        type="text"
        name="title"
        placeholder="Event Title"
      />
      <Input label="Start" type="datetime-local" name="start_time" />
      <Input label="End" type="datetime-local" name="end_time" />
      <Input
        label="Adult volunteers needed"
        type="number"
        name="adult_slots"
      />
      <Input
        label="Teenager volunteers needed"
        type="number"
        name="teenager_slots"
      />
      <Input label="Event description" type="text" name="description" />
      <Input label="Team ID" type="number" name="team_id" />

      <Button type="submit" label="Create event" />
    </form>
  );
};
