"use client";
import { useEffect, useState } from "react";
import { createEvent, IEvent, eventSchema } from "@/app/events/events.service";
import { Input } from "../../components/Input";
import { Button } from "@/app/components/Button";
import { IToast, Toast } from "@/app/components/Toast";
import {
  formatDateTime,
  validateOnBlur,
  calculateEndTime,
} from "@/app/utilities";
import { eventDuration } from "../events.helper";
import { DropDown } from "@/app/components/DropDown";
import { MarkdownEditor } from "@/app/components/MarkdownEditor";

export const CreateEventForm = ({ teams }: { teams: any }) => {
  const today = formatDateTime(
    new Date().toISOString(),
    {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    },
    "en-CA"
  );
  const dateOptions: Intl.DateTimeFormatOptions = {
    dateStyle: "long",
  };
  const timeOptions: Intl.DateTimeFormatOptions = {
    timeStyle: "short",
  };
  const [toast, setToast] = useState<IToast>();
  const [errors, setErrors] = useState<{ [name: string]: string }>({});
  const [startDate, setStartDate] = useState(today);
  const [endDate, setEndDate] = useState(today);
  const [startTime, setStartTime] = useState("");
  const [hours, setHours] = useState("1");
  const [endTime, setEndTime] = useState("");
  const [duration, setDuration] = useState<string | undefined>();
  const [description, setDescription] = useState<string>("");
  const [disable, setDisable] = useState<boolean>();
  const [showCustomTime, setShowCustomTime] = useState(false);

  const handleChange = async (
    event: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    validateOnBlur(event, eventSchema, setErrors);
  };

  const handleMarkdownChange = (value: string) => {
    setDescription(value);
  };

  const handleStartTime = (value: string) => {
    setStartTime(value);
    const endDateAndTime = calculateEndTime(startDate, value, hours);
    setEndDate(endDateAndTime[0]);
    setEndTime(endDateAndTime[1]);
  };

  const handleQuickSelect = () => {
    setShowCustomTime(false);
    handleHours(hours);
  };

  const handleHours = (value: string) => {
    if (value === "custom") {
      setShowCustomTime(true);
      return;
    }
    setHours(value);
    const endDateAndTime = calculateEndTime(startDate, startTime, value);
    setEndDate(endDateAndTime[0]);
    setEndTime(endDateAndTime[1]);
  };

  const submitEventInformation = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const formEntries = Object.fromEntries(formData);
    const formStartTime = startDate + " " + startTime;
    const formEndTime = endDate + " " + endTime;
    const event: IEvent = {
      // id is generated by backend, so it is omitted here
      title: formEntries.title as string,
      description: formEntries.description as string,
      start_time: formStartTime,
      end_time: formEndTime,
      adult_slots: Number(formEntries.adult_slots),
      teenager_slots: Number(formEntries.teenager_slots),
      // creator id is set to current_user.id in the events_controller create action
      team_id: Number(formEntries.team_id),
    };
    try {
      eventSchema.validateSync(formEntries, {
        abortEarly: false,
      });
      createEvent(event)
        .then(async (response) => {
          setDisable(true);
          setToast({
            message: "Event created",
            status: "success",
          });
          setTimeout(() => {
            window.location.href = `/events/${response.id}`;
          }, 1000);
        })
        .catch((error) => {
          setToast({ message: error.message, status: "error" });
        });
    } catch (validationError: any) {
      const formattedError = validationError.inner.reduce(
        (acc: any, err: any) => {
          acc[err.path] = err.message;
          return acc;
        },
        {}
      );
      setErrors(formattedError);
    }
  };

  useEffect(() => {
    if (startTime && endTime) {
      const startDateAndTime = `${startDate} ${startTime}`;
      const endDateAndTime = `${endDate} ${endTime}`;
      setDuration(eventDuration(startDateAndTime, endDateAndTime));
    }
  }, [startDate, endDate, startTime, endTime]);

  return (
    <>
      {toast && (
        <Toast
          message={toast.message}
          status={toast.status}
          onClose={() => setToast(undefined)}
        />
      )}

      <form onSubmit={submitEventInformation} className="flex flex-col gap-4">
        <div className="flex flex-col gap-4 max-w-100">
          <Input
            label="Event title"
            type="text"
            name="title"
            onBlur={handleChange}
            errorMessage={errors.title}
          />
          {!showCustomTime && (
            <>
              <Input
                label="Start Date"
                type="date"
                name="start_date"
                defaultValue={startDate}
                onInput={(e) => {
                  setStartDate(e.currentTarget.value);
                }}
                onFocus={(e) => e.currentTarget.showPicker()}
              />
              <div className="flex gap-4 max-w-100 items-center">
                <Input
                  type="time"
                  name="start_time"
                  label="Start time"
                  onFocus={(e) => e.currentTarget.showPicker()}
                  defaultValue={startTime}
                  onChange={(e) => handleStartTime(e.target.value)}
                  onBlur={handleChange}
                  errorMessage={errors.start_time}
                />
                <div>
                  <DropDown
                    choices={[
                      "1",
                      "1.5",
                      "2",
                      "2.5",
                      "3",
                      "3.5",
                      "4",
                      "custom",
                    ]}
                    label="Hour(s)"
                    helpText=""
                    onChange={(e) => handleHours(e.target.value)}
                    defaultValue={hours}
                  />
                  <Input
                    type="hidden"
                    name="end_time"
                    defaultValue={endTime}
                    onBlur={handleChange}
                    errorMessage={errors.end_time}
                  />
                </div>
              </div>
              {endTime &&
                `Ends on ${formatDateTime(
                  `${endDate} ${endTime}`,
                  dateOptions
                )} at ${formatDateTime(`${endDate} ${endTime}`, timeOptions)}`}
            </>
          )}
          {showCustomTime && (
            <>
              <div className="flex gap-4 max-w-100 items-center">
                <Input
                  label="Start Date"
                  type="date"
                  name="start_date"
                  defaultValue={startDate}
                  onInput={(e) => {
                    setStartDate(e.currentTarget.value);
                  }}
                  onFocus={(e) => e.currentTarget.showPicker()}
                />
                <Input
                  type="time"
                  name="start_time"
                  label="Start time"
                  onFocus={(e) => e.currentTarget.showPicker()}
                  defaultValue={startTime}
                  onChange={(e) => setStartTime(e.target.value)}
                  onBlur={handleChange}
                  errorMessage={errors.start_time}
                />
              </div>
              <div className="flex gap-4 max-w-100 items-center">
                <Input
                  label="End Date"
                  type="date"
                  name="end_date"
                  defaultValue={endDate}
                  onInput={(e) => {
                    setEndDate(e.currentTarget.value);
                  }}
                  onFocus={(e) => e.currentTarget.showPicker()}
                />
                <Input
                  type="time"
                  name="end_time"
                  label="End time"
                  onFocus={(e) => e.currentTarget.showPicker()}
                  defaultValue={endTime}
                  onChange={(e) => setEndTime(e.target.value)}
                  onBlur={handleChange}
                  errorMessage={errors.end_time}
                />
              </div>
              <div className="flex justify-start">
                <Button
                  type="button"
                  onClick={handleQuickSelect}
                  label="Back to quick select"
                />
              </div>
              {duration && <p>Duration: {duration}</p>}
            </>
          )}
          <Input
            label="Adult volunteers needed"
            type="number"
            name="adult_slots"
            onBlur={handleChange}
            errorMessage={errors.adult_slots}
          />
          <Input
            label="Teenager volunteers needed"
            type="number"
            name="teenager_slots"
            onBlur={handleChange}
            errorMessage={errors.teenager_slots}
          />
          <Input
            label="Time when signups are closed"
            type="datetime-local"
            name="close_time"
            defaultValue={startDate + "T" + startTime}
          />
          <DropDown
            choices={teams}
            name="team_id"
            label="Team"
            helpText="Please select a team"
            onBlur={handleChange}
            errorMessage={errors.team_id}
          />
        </div>
        <div>
          <input name="description" type="hidden" value={description} />
          <MarkdownEditor
            label="Event description"
            onChange={handleMarkdownChange}
          />
        </div>

        <Button type="submit" label="Create event" disabled={disable} />
      </form>
    </>
  );
};
