"use client";
import { createEvent, IEvent } from "@/app/events/events.service";
import { Button } from "@/app/components/Button";
import { Input } from "@/app/components/Input";
import { Textarea } from "@/app/components/Textarea";
import { isoDateTime, validateOnBlur } from "@/app/utilities";
import { useEffect, useState } from "react";
import { IToast, Toast } from "@/app/components/Toast";
import { object, string } from "yup";
import { eventDuration } from "../../events.helper";
import { MarkdownEditor } from "@/app/components/MarkdownEditor";

interface ICloneEventForm {
  eventData: IEvent;
}

export const CloneEventForm = ({ eventData }: { eventData: IEvent }) => {
  const [startTime, setStartTime] = useState(eventData.start_time);
  const [endTime, setEndTime] = useState(eventData.end_time);
  const [description, setDescription] = useState<string>("");
  const [disable, setDisable] = useState<boolean>();
  const [duration, setDuration] = useState<string | undefined>();
  const [toast, setToast] = useState<IToast>();
  const [errors, setErrors] = useState<{ [name: string]: string }>({});
  const eventSchema = object({
    title: string().required("Event title is required"),
    description: string().required("Event description is required"),
    start_time: string().required("Start time is required"),
    end_time: string().required("End time is required"),
    adult_slots: string().required("Adult slots is required"),
    teenager_slots: string().required("Teenager slots is required"),
    team_id: string().required("Team ID is required"),
  });

  const handleChange = async (
    event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    validateOnBlur(event, eventSchema, setErrors);
  };

  const handleMarkdownChange = (value: string) => {
    setDescription(value);
  };

  const submitEventInformation = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const formEntries = Object.fromEntries(formData);
    const event: IEvent = {
      // id is generated by backend, so it is omitted here
      title: formEntries.title as string,
      description: formEntries.description as string,
      start_time: formEntries.start_time as string,
      end_time: formEntries.end_time as string,
      adult_slots: Number(formEntries.adult_slots),
      teenager_slots: Number(formEntries.teenager_slots),
      // creator id is set to current_user.id in the events_controller create action
      team_id: Number(formEntries.team_id),
    };
    try {
      eventSchema.validateSync(formEntries, {
        abortEarly: false,
      });
      createEvent(event)
        .then(async (response) => {
          if (response.id) {
            setToast({
              message: "Event clone created",
              status: "success",
            });
            setTimeout(() => {
              window.location.href = `/events/${response.id}`;
            }, 1000);
          } else {
            setToast({
              message: "Error creating event",
              status: "error",
            });
          }
        })
        .catch((error) => {
          setToast({ message: error.message, status: "error" });
        });
    } catch (validationError: any) {
      const formattedError = validationError.inner.reduce(
        (acc: any, err: any) => {
          acc[err.path] = err.message;
          return acc;
        },
        {}
      );
      setErrors(formattedError);
    }
  };

  useEffect(() => {
    if (startTime && endTime) {
      setDuration(eventDuration(startTime, endTime));
    }
  }, [startTime, endTime]);

  return (
    <>
      {toast && (
        <Toast
          message={toast.message}
          status={toast.status}
          onClose={() => setToast(undefined)}
        />
      )}
      <form onSubmit={submitEventInformation} className="flex flex-col gap-4">
        <div className="flex flex-col gap-4 max-w-100">
          <Input
            label="Event Title"
            type="text"
            name="title"
            placeholder="Event Title"
            defaultValue={`${eventData?.title} Clone`}
            onBlur={handleChange}
            errorMessage={errors.title}
          />
          <Input
            label="Start"
            type="datetime-local"
            name="start_time"
            defaultValue={
              eventData?.start_time && isoDateTime(eventData?.start_time)
            }
            onBlur={handleChange}
            onInput={(e) => {
              setStartTime(e.currentTarget.value);
            }}
            errorMessage={errors.start_time}
          />
          <Input
            label="End"
            type="datetime-local"
            name="end_time"
            defaultValue={
              eventData?.end_time && isoDateTime(eventData?.end_time)
            }
            onBlur={handleChange}
            onInput={(e) => {
              setEndTime(e.currentTarget.value);
            }}
            errorMessage={errors.end_time}
          />
          {duration && <p>Duration: {duration}</p>}
          <Input
            label="Adult volunteers needed"
            type="number"
            name="adult_slots"
            defaultValue={eventData?.adult_slots}
            onBlur={handleChange}
            errorMessage={errors.adult_slots}
          />
          <Input
            label="Teenager volunteers needed"
            type="number"
            name="teenager_slots"
            defaultValue={eventData?.teenager_slots}
            onBlur={handleChange}
            errorMessage={errors.teenager_slots}
          />
          <Input
            label="Team ID"
            type="number"
            name="team_id"
            defaultValue={eventData?.team_id}
            onBlur={handleChange}
            errorMessage={errors.team_id}
          />
        </div>
        <div>
          <input name="description" type="hidden" value={description} />
          <MarkdownEditor
            label="Event description"
            defaultValue={eventData?.description}
            onChange={handleMarkdownChange}
          />
        </div>

        <Button type="submit" label="Save clone as new event" disabled={disable} />
      </form>
    </>
  );
};

export default CloneEventForm;
